rm(list = ls())
cat("\014")

# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3,5,6 and 9. The sum of these multiples is 23.Find the sum of all
#multiples of 3 or 5 below 1000.


# initialize a counter

sum <- 0

#create a loop and then check if a number is a multiple of 3 or 5. If it is, add to counter

for (i in 1:999) {
  
  if (i %% 3 == 0 || i %% 5 == 0) {
    sum = sum + i
  }
}

print(sum)

# sum = 233,168


# Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

# initialize fibonacci counter
sum <- 0
first <- 1
second <- 2

# create a while loop, sum even values, and continue to produce next numbers
while (first <= 4000000) {
  
  if (first %% 2 == 0) {
    sum = sum + first
  }
  next_num <- first + second
   first <- second
   second <- next_num
  
}

print(sum)

# sum = 4,613,732


# the prime factors of 13195 are 5,7,13,29
# what is the largest prime factor of the number 600851475143


num <- 600851475143
largest <- 0

# find all integers that our number is divisible by that leave no remainder
# check if these integers are primes

for (i in 2:num-1) {
  if (num %% i == 0) {
    prime <- TRUE
    for (j in 2:i-1) {
      if (j %% i == 0) {
        prime <- FALSE
        break
      }
    }
    if(prime) {
      largest <- i
    }
  }
}

print(largest)

# largest = 6,857

